Importing Pandas and Numpy

In [50]:
import pandas as pd
import numpy as np

Qu 1: Check Pandas Version

In [23]:
pd.__version__

'2.1.0'

Import Dataset

In [36]:
dataset = pd.read_csv("house_dataset.csv")

In [25]:
dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


Q2:Check Number of columns

In [6]:
len(dataset.columns)

10

Q3: Check columns with null values

In [8]:
dataset.columns[dataset.isnull().any()]


Index(['total_bedrooms'], dtype='object')

In [26]:
print(dataset.isnull().sum())


longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


Q4: Check Unique values ni Column ocean_proximity

In [27]:
dataset['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

Q 5: Check Mean of  median_house_value of Near Bay

In [28]:
mean_val =dataset.loc[dataset['ocean_proximity'] == 'NEAR BAY', 'median_house_value'].mean()

In [35]:
mean_val.round(decimals = 3)

259212.312

Q6: Fill null values in total_bedrooms with mean_val and find the mean if changes

In [38]:
dataset['total_bedrooms']=dataset['total_bedrooms'].fillna(mean_val)

In [39]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [41]:
dataset.loc[dataset['ocean_proximity'] == 'NEAR BAY', 'median_house_value'].mean()

259212.31179039303

Q7: Value of the last element of w


In [44]:
islands_dataset = dataset[dataset['ocean_proximity'] == 'ISLAND']


In [46]:
islands_dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [47]:
cols = ['housing_median_age', 'total_rooms', 'total_bedrooms']

In [48]:
new_dataset = islands_dataset[cols]


In [49]:
new_dataset.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [51]:
X = new_dataset.values

In [56]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [52]:
XTX = np.dot(X.T, X)

In [55]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [53]:
XTX_inverse = np.linalg.inv(XTX)


In [54]:
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [57]:
y = np.array([950, 1300, 800, 1000, 1300])

In [58]:
y

array([ 950, 1300,  800, 1000, 1300])

In [60]:
w = np.dot(np.dot(XTX_inverse, X.T), y)

In [61]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [62]:
tail_element = w[-1]


In [63]:
tail_element

5.699229455065586